Create w3c.json
w3c/vc-bitstring-status-list-test-suite pull request #44
Opened 2024-09-18 20:39 UTC by plehegar

You need one of those.

This is assuming this project belongs to the VC WG.

2024-09-19 07:07 UTC, iherman approved these changes
My bad, I missed that at the time. Thanks for this.

2024-09-19 07:09 UTC, iherman commented
@BigBlueHat this should be merged ASAP. I did not want to do that, because I did not know whether the github workflow would be triggered and, if yes, what it would mean to the repository.

2024-11-05 16:29 UTC, BigBlueHat requested changes
I'd left this feedback awhile ago...but clearly didn't submit it properly... 🤦‍♂️ 

@PatStLouis we should get this merged with my suggested change at your earliest convenience. Thanks!

2024-11-05 16:52 UTC, BigBlueHat approved these changes

2024-11-05 16:53 UTC, merged